#### Wine dataset
The wine dataset is a classic and very easy multi-class classification dataset.

You can load the dataset from sklearn (it is a preloaded dataset)

In [1]:
#importing necessary library for analysis
import pandas as pd 
import numpy as np

#importing dataset
from sklearn.datasets import load_wine

In [2]:
#creating an instance of dataset
wine=load_wine()

In [3]:
#to see whats in the dataset
print(wine.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [4]:
# taking a look at description 
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [5]:
#printing all the data
print(wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [6]:
#the targets name 
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [7]:
#the columns name
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [8]:
# Loading the dataset into pandas
df=pd.DataFrame(wine.data)

# printing first five rows of data
df.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

Since the dataset contains no header, we will load the headers by feature_names

In [9]:
#adding header to the dataset
df.columns=wine.feature_names

#taking a look at the dataset
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [10]:
#checking the info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [11]:
# taking a look at the statistics
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [12]:
#dividing the original i.e. wine dataset into X and Y variable
X=wine.data
Y=wine.target

#printing the shape of X and Y
print(X.shape)
print(Y.shape)

(178, 13)
(178,)


#### Splitting the data
Dividing the dataset into train and test

In [13]:
#importing train_test_split 
from sklearn.model_selection import train_test_split

#dividing
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=2)

Normalizing the data using Standard scaler library to do a better fit to the model

In [14]:
# importing necessary modules
from sklearn.preprocessing import StandardScaler

# creating an instance
sc=StandardScaler()

# transforming the X_train and X_test variable
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

Now, its time to train the model using classification model. We will use Logistic Regression for multi-class classification.

#### Training the dataset

In [15]:
#importing Logistic Regression
from sklearn.linear_model import LogisticRegression

#creating an instance of the model
model=LogisticRegression()

In [16]:
#fitting the training data into the model
model.fit(X_train,Y_train)

LogisticRegression()

We can do the prediction and check the accuracy of the model by sklearn module called accuracy_score

We will check both the train and test data accuracy

In [17]:
#importing necessary library 
from sklearn.metrics import accuracy_score

In [18]:
#Checking the accuracy on train data
y_pred_train=model.predict(X_train)
acc=accuracy_score(Y_train,y_pred_train)
print('Accuracy on train data :',acc*100)

Accuracy on train data : 100.0


In [19]:
#Checking the accuracy on train data
y_pred_test=model.predict(X_test)
acc=accuracy_score(Y_test,y_pred_test)
print('Accuracy on test data :',acc*100)

Accuracy on test data : 100.0


So our model is giving 100 % accuracy on both test and train data

Lets see the confusion matrix of the model

In [20]:
# importing confusion matrix from sklearn
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_pred_test)
print('Confusion matrix of test data :\n',cm)

Confusion matrix of test data :
 [[20  0  0]
 [ 0 20  0]
 [ 0  0 14]]


In [21]:
cm=confusion_matrix(Y_train,y_pred_train)
print('Confusion matrix of train data :\n',cm)

Confusion matrix of train data :
 [[39  0  0]
 [ 0 51  0]
 [ 0  0 34]]


#### Validating the model
Lets validate the model by giving it new values and checking how it is predicting the result

In [22]:
#giving input (taking a random value from the dataset)
input=(14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0)

# converting the input into numpy array 
inp_array=np.asarray(input)

#checking the shape of the input
print(inp_array.shape)

(13,)


In [23]:
#converting the input into 2d array
inp_reshape=inp_array.reshape(1,-1)

#checking the shape of the array
print(inp_reshape.shape)

(1, 13)


In [24]:
#predicting the output
output=model.predict(inp_reshape)
if output==wine.target[0]:
    print('class0')

class0


So our model is predicted correct output which is class0

## Thank You